version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
    ports:
      - "80:80"
      - "8080:8080"
    tty: true
    stdin_open: true

  nginx:
    image: nginx:latest
    network_mode: "service:app"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
